theme: minima
title: Github is great!
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Githun lab is awsomee and should be used for people who have had minimal experience.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
